version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'obm'
      POSTGRES_USER: 'obm'
      POSTGRES_DB: 'obm'
      POSTGRES_PASSWORD: 'obm'

  api:
    build: 
      context: .
      dockerfile: docker/api/Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DEBUG: 'True'
      SECRET_KEY: '(ie3e8$p^6m8oi&j0-80@(fu#i*9)#cvv5*4@(q9@4ozzrm6uu'
      DB_NAME: 'obm'
      DB_USER: 'obm'
      DB_PASSWORD: 'obm'
      DB_HOST: 'db'
      DB_PORT: '5432'  
    command: python manage.py runserver
 
volumes:
  postgres_data: