# Generated by Django 2.2.2 on 2019-06-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190612_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='infix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='member',
            name='jobtitle',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
