# Generated by Django 2.2.2 on 2019-06-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190612_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='photo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
